#region Usings

// #region Usings: Specifies the namespaces that the class depends on.
using System.Windows;

#endregion

namespace ScratchCardGenerator.Views
{
    /// <summary>
    /// Interaction logic for AdvancedAnalysisWindow.xaml.
    /// As per MVVM best practices, the code-behind for this window is minimal.
    /// All logic for data calculation and presentation is handled by the AdvancedAnalysisViewModel.
    /// </summary>
    public partial class AdvancedAnalysisWindow : Window
    {
        #region Constructor

        /// <summary>
        /// Initialises a new instance of the <see cref="AdvancedAnalysisWindow"/> class.
        /// </summary>
        public AdvancedAnalysisWindow()
        {
            // This method, generated by the XAML designer, initialises all the UI components
            // defined in the corresponding .xaml file and wires up their events.
            InitializeComponent();
        }

        #endregion
    }
}