#region Usings

// #region Usings: Specifies the namespaces that the class depends on.
using System.Windows;

#endregion

namespace ScratchCardGenerator.Views
{
    /// <summary>
    /// Interaction logic for HelpGuideWindow.xaml. This window displays a formatted
    /// help document to the user. All content is defined within the XAML file.
    /// </summary>
    public partial class HelpGuideWindow : Window
    {
        #region Constructor

        /// <summary>
        /// Initialises a new instance of the <see cref="HelpGuideWindow"/> class.
        /// </summary>
        public HelpGuideWindow()
        {
            // This method, generated by the XAML designer, initialises all the UI components
            // defined in the corresponding .xaml file.
            InitializeComponent();
        }

        #endregion

        #region Event Handlers

        /// <summary>
        /// Handles the Click event for the Close button.
        /// </summary>
        /// <param name="sender">The source of the event (the Button).</param>
        /// <param name="e">An object that contains no event data.</param>
        private void CloseButton_Click(object sender, RoutedEventArgs e)
        {
            // Closes the Help Guide window.
            this.Close();
        }

        #endregion
    }
}