#region Usings

// #region Usings: Specifies the namespaces that the class depends on.
using System.Text;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;

#endregion

namespace FinalGameChecker
{
    /// <summary>
    /// Interaction logic for MainWindow.xaml.
    /// In a well-structured MVVM application, this code-behind file should contain minimal logic.
    /// Its primary responsibility is to initialise the component, with all application logic and state
    /// being handled by the associated ViewModel (CheckerViewModel).
    /// </summary>
    public partial class MainWindow : Window
    {
        #region Constructor

        /// <summary>
        /// Initialises a new instance of the <see cref="MainWindow"/> class.
        /// </summary>
        public MainWindow()
        {
            // This method, generated by the XAML designer, initialises all the UI components
            // defined in the corresponding MainWindow.xaml file and wires up their events.
            InitializeComponent();
        }

        #endregion
    }
}
