#region Usings

// #region Usings: Specifies the namespaces that the class depends on.
using ScratchCardGenerator.Common.Models;
using System.Collections.Generic;
using System.Text.Json.Serialization;

#endregion

namespace ScratchCardGenerator.Common.Models
{
    /// <summary>
    /// Represents a single, generated scratch card ticket, including its overall win status
    /// and the specific data generated by each game module on it. This object is a key data structure
    /// used during the generation process and for serialising the final ticket data to JSON files.
    /// </summary>
    public class Ticket
    {
        #region Properties

        /// <summary>
        /// Gets or sets the overall prize tier won by this ticket. If the ticket is a loser,
        /// this will be a reference to the project's "NO WIN" prize tier (where Value is 0).
        /// </summary>
        public PrizeTier WinPrize { get; set; }

        /// <summary>
        /// Gets or sets a list holding the generated play data for each game module on this ticket.
        /// Each entry in the list corresponds to the output of a single game module on the card layout.
        /// </summary>
        public List<GamePlayData> GameData { get; set; }

        #endregion

        #region Constructor

        /// <summary>
        /// Initialises a new instance of the <see cref="Ticket"/> class.
        /// </summary>
        public Ticket()
        {
            // The GameData list is initialised in the constructor to ensure it is never null,
            // preventing NullReferenceExceptions when game modules attempt to add their play data to it.
            GameData = new List<GamePlayData>();
        }

        #endregion
    }
}